### ISSUE TITLE
503 error

### ISSUE THREAD

**Issue by samk1r0** [eza/lnurl-php#1]
Hi! Thanks for your great tutorial on logging in using lnurl, however When I try to implement what you've done I get 503 error like on the screenshot as I try to do the first step(log in using alby chrome extension)
![image](https://github.com/eza/lnurl-php/assets/36104994/7c554e64-8a70-4ba3-a2fd-3c596efc0f1b)

**Comment by eza** [comment]
hi have you considered it might be an issue with Alby, try an another wallet like Breez

**Comment by samk1r0** [comment]
yeah it seems like this is a problem on Alby site since as I login using breeze my webpage receives the webhook

**Comment by eza** [comment]
brilliant. closing this now
